### ISSUE TITLE
error with 7.2.1

### ISSUE THREAD

**Issue by farberm** [FlyingDiver/BetterEmail#7]
I am getting the following error

Traceback (most recent call last):
  File "plugin.py", line 276, in runConcurrentThread
  File "/Library/Application Support/Perceptive Automation/Indigo 7/Plugins/BetterEmail.indigoPlugin/Contents/Server Plugin/IMAPServer.py", line 74, in pollCheck
AttributeError: 'IMAPServer' object has no attribute 'next_poll'

   Better Email Error              plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Better Email Error              Error in plugin execution runConcurrentThread:

Any suggestions?

**Comment by FlyingDiver** [comment]
Are you using IMAP IDLE?

**Comment by FlyingDiver** [comment]
Fixed in 7.2.2.
